int show1();
int choiceOp(int option);
void exit();
int addsController();
int addController();
int isExist(PeopleInfo *allPeople,PeopleInfo *people);
PeopleInfo *isExistByName(PeopleInfo *postion,PeopleInfo *people);
int delController();
void saveController();
void initDate();